name: penoval_usi702_eraser_fix
description: Workaround to get the eraser to work on the penoval USI702 (and possibly other pens with a similar issue)
version: 1.0.0
repository: https://github.com/Aegeontis/penoval-usi702-eraser-fix

environment:
  sdk: ^3.5.3

dependencies:
  args: ^2.5.0
  http: ^1.2.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
